# Generated by Django 5.0.7 on 2024-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('b64_img', models.TextField(blank=True, null=True)),
                ('img_dhash', models.CharField(max_length=255)),
                ('h_dist', models.IntegerField()),
                ('loc', models.CharField(max_length=255)),
            ],
        ),
    ]
