# Generated by Django 5.0.7 on 2024-08-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
